### ISSUE TITLE
Too many files in py.test

### ISSUE THREAD

**Issue by eugene-bulkin** [PHB-CS123/graphene#23]
On occasion, running the tests will open too many file descriptors due to things not being properly disposed of in storage manager... Thought this was fixed with a9b8a26 but apparently it is not entirely taken care of yet.

**Comment by codyhan94** [comment]
Current workaround is to increase the number of available file handles on the host OS.

**Comment by eugene-bulkin** [comment]
I think this is finally fixed. Major issues were as follows:
- Garbage collection in Python. The `__del__` magic method is not called unless _every_ reference has been removed, so even though we thought we were cleaning up in tests, we actually were not. This was fixed by adding a `close` method and calling that manually, and `__del__` just calls that.
- LRU caches were not being cleaned. The LRU caches stored a reference to the storage manager, so the storage manager could never be cleaned up since it never cleaned up the LRU caches. Once this was handled everything worked.
